# Generated by Django 4.0.4 on 2022-05-21 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('badgeNo', models.IntegerField(unique=True)),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('dob', models.DateField()),
                ('collegeId', models.IntegerField()),
                ('status', models.CharField(default='Active', max_length=50)),
                ('email', models.EmailField(max_length=254, unique=b'I01\n')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
