# Generated by Django 4.0.4 on 2022-05-21 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_is_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badgeNo',
            field=models.IntegerField(),
        ),
    ]
