# Generated by Django 4.0.4 on 2022-05-21 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='badgeNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='collegeId',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstName',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastName',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
