# Generated by Django 4.0.4 on 2022-05-26 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_inceidents_alter_user_email_muleinspection_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='inceidents',
            new_name='inceident',
        ),
    ]
