# Generated by Django 4.0.4 on 2022-06-02 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_rename_inceidents_inceident'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationName', models.CharField(max_length=150, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='incidentreport',
            name='location',
            field=models.CharField(default='temp', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='inceident',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='academicLockup',
        ),
    ]
