# Generated by Django 3.2.3 on 2022-08-19 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_location_incidentreport_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='locationDetail',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='inceident',
            name='inceidentName',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='incidentreport',
            name='inceident',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='muleInspection',
        ),
    ]
