# Generated by Django 3.2.3 on 2022-08-19 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20220819_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidentreport',
            name='locationDetail',
        ),
    ]
