# Generated by Django 3.2.3 on 2022-08-21 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_remove_incidentreport_locationdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidentreport',
            name='locationDetail',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.CreateModel(
            name='referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=150)),
                ('middleInitial', models.CharField(max_length=150)),
                ('ICID', models.CharField(max_length=150)),
                ('dob', models.DateField()),
                ('address', models.TextField()),
                ('phoneNo', models.CharField(max_length=150)),
                ('incidentReport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.incidentreport')),
            ],
        ),
    ]
