# Generated by Django 4.1 on 2022-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_clockedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timecard',
            name='submitedDate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='clockedin',
            name='start',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
