# Generated by Django 4.1 on 2022-08-21 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_timecard_approval_timecard_submiteddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='submitedDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
