# Generated by Django 4.1 on 2022-08-22 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_timecard_submiteddate'),
    ]

    operations = [
        migrations.AddField(
            model_name='timecard',
            name='note',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
