# Generated by Django 4.1 on 2022-08-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_timecard_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Probationary Member', max_length=150, null=True),
        ),
    ]
