# Generated by Django 4.1 on 2022-08-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_user_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='duration',
            field=models.DurationField(),
        ),
    ]
