# Generated by Django 4.1 on 2022-08-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_timecard_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='duration',
            field=models.CharField(max_length=150),
        ),
    ]
