# Generated by Django 4.1 on 2022-08-23 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_alter_timecard_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
