# Generated by Django 4.1 on 2022-08-23 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_alter_timecard_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='approval',
            field=models.CharField(max_length=150),
        ),
    ]
