# Generated by Django 3.2.3 on 2022-08-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_timecard_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timecard',
            name='approval',
            field=models.CharField(default='Pending', max_length=150),
        ),
    ]
